# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/service.proto\x12\x12\x66\x65\x64\x65rated_learning\"\x8b\x01\n\nFitRequest\x12\x12\n\nparameters\x18\x01 \x01(\x0c\x12:\n\x06\x63onfig\x18\x02 \x03(\x0b\x32*.federated_learning.FitRequest.ConfigEntry\x1a-\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xa6\x01\n\x0b\x46itResponse\x12\x12\n\nparameters\x18\x01 \x01(\x0c\x12\x14\n\x0cnum_examples\x18\x02 \x01(\x05\x12=\n\x07metrics\x18\x03 \x03(\x0b\x32,.federated_learning.FitResponse.MetricsEntry\x1a.\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"\x95\x01\n\x0f\x45valuateRequest\x12\x12\n\nparameters\x18\x01 \x01(\x0c\x12?\n\x06\x63onfig\x18\x02 \x03(\x0b\x32/.federated_learning.EvaluateRequest.ConfigEntry\x1a-\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xaa\x01\n\x10\x45valuateResponse\x12\x0c\n\x04loss\x18\x01 \x01(\x02\x12\x14\n\x0cnum_examples\x18\x02 \x01(\x05\x12\x42\n\x07metrics\x18\x03 \x03(\x0b\x32\x31.federated_learning.EvaluateResponse.MetricsEntry\x1a.\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x32\xb9\x01\n\x18\x46\x65\x64\x65ratedLearningService\x12\x46\n\x03\x46it\x12\x1e.federated_learning.FitRequest\x1a\x1f.federated_learning.FitResponse\x12U\n\x08\x45valuate\x12#.federated_learning.EvaluateRequest\x1a$.federated_learning.EvaluateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FITREQUEST_CONFIGENTRY']._loaded_options = None
  _globals['_FITREQUEST_CONFIGENTRY']._serialized_options = b'8\001'
  _globals['_FITRESPONSE_METRICSENTRY']._loaded_options = None
  _globals['_FITRESPONSE_METRICSENTRY']._serialized_options = b'8\001'
  _globals['_EVALUATEREQUEST_CONFIGENTRY']._loaded_options = None
  _globals['_EVALUATEREQUEST_CONFIGENTRY']._serialized_options = b'8\001'
  _globals['_EVALUATERESPONSE_METRICSENTRY']._loaded_options = None
  _globals['_EVALUATERESPONSE_METRICSENTRY']._serialized_options = b'8\001'
  _globals['_FITREQUEST']._serialized_start=45
  _globals['_FITREQUEST']._serialized_end=184
  _globals['_FITREQUEST_CONFIGENTRY']._serialized_start=139
  _globals['_FITREQUEST_CONFIGENTRY']._serialized_end=184
  _globals['_FITRESPONSE']._serialized_start=187
  _globals['_FITRESPONSE']._serialized_end=353
  _globals['_FITRESPONSE_METRICSENTRY']._serialized_start=307
  _globals['_FITRESPONSE_METRICSENTRY']._serialized_end=353
  _globals['_EVALUATEREQUEST']._serialized_start=356
  _globals['_EVALUATEREQUEST']._serialized_end=505
  _globals['_EVALUATEREQUEST_CONFIGENTRY']._serialized_start=139
  _globals['_EVALUATEREQUEST_CONFIGENTRY']._serialized_end=184
  _globals['_EVALUATERESPONSE']._serialized_start=508
  _globals['_EVALUATERESPONSE']._serialized_end=678
  _globals['_EVALUATERESPONSE_METRICSENTRY']._serialized_start=307
  _globals['_EVALUATERESPONSE_METRICSENTRY']._serialized_end=353
  _globals['_FEDERATEDLEARNINGSERVICE']._serialized_start=681
  _globals['_FEDERATEDLEARNINGSERVICE']._serialized_end=866
# @@protoc_insertion_point(module_scope)
