# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import service_pb2 as protos_dot_service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FederatedLearningServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Fit = channel.unary_unary(
                '/federated_learning.FederatedLearningService/Fit',
                request_serializer=protos_dot_service__pb2.FitRequest.SerializeToString,
                response_deserializer=protos_dot_service__pb2.FitResponse.FromString,
                _registered_method=True)
        self.Evaluate = channel.unary_unary(
                '/federated_learning.FederatedLearningService/Evaluate',
                request_serializer=protos_dot_service__pb2.EvaluateRequest.SerializeToString,
                response_deserializer=protos_dot_service__pb2.EvaluateResponse.FromString,
                _registered_method=True)


class FederatedLearningServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Fit(self, request, context):
        """Client receives model parameters from Server and returns updated parameters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Evaluate(self, request, context):
        """Optional: Evaluate the model on the client
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederatedLearningServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Fit': grpc.unary_unary_rpc_method_handler(
                    servicer.Fit,
                    request_deserializer=protos_dot_service__pb2.FitRequest.FromString,
                    response_serializer=protos_dot_service__pb2.FitResponse.SerializeToString,
            ),
            'Evaluate': grpc.unary_unary_rpc_method_handler(
                    servicer.Evaluate,
                    request_deserializer=protos_dot_service__pb2.EvaluateRequest.FromString,
                    response_serializer=protos_dot_service__pb2.EvaluateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'federated_learning.FederatedLearningService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('federated_learning.FederatedLearningService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FederatedLearningService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Fit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated_learning.FederatedLearningService/Fit',
            protos_dot_service__pb2.FitRequest.SerializeToString,
            protos_dot_service__pb2.FitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Evaluate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated_learning.FederatedLearningService/Evaluate',
            protos_dot_service__pb2.EvaluateRequest.SerializeToString,
            protos_dot_service__pb2.EvaluateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
